// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateMentions() {
  return window['go']['eventbucket']['EventBucket']['CalculateMentions']();
}

export function CurrentOrder() {
  return window['go']['eventbucket']['EventBucket']['CurrentOrder']();
}
