// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {eventbucket} from '../models';

export function CalculateMentions():Promise<boolean>;

export function CurrentOrder():Promise<Array<eventbucket.Event>>;
